config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root    'sessions#new'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'
  delete  'logout'        =>  'sessions#destroy'
  resources :profiles
  get 'invite_user', to: 'profiles#invite'
  get 'send_invitation', to: 'profiles#send_invitation'
  resources :champions, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'search_summoner', to: 'search#search'
  get 'search_to_invite', to: 'search#search_to_invite'
  resources :friendships, only: [:new, :edit, :index, :destroy]
  get 'decide_friendships', to: 'friendships#decide'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_user, only: [:show]
  before_action :check_or_set_user, except: [:index]

  def index
  end

  def show
    @user = User.exists?(id: params[:id]) ? User.find(params[:id]) : current_user
    featured_stats_service = FeaturedStatsService.new(@user)
    @featured_stats = featured_stats_service.featured_stats
    @overall_stats = featured_stats_service.overall_stats
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else 
      render 'new'
    end
  end
    
  def send_invitation
    if params[:summoner_email].nil?
      flash[:danger] = "Summoner email is required."
      redirect_to :back
    else
      email = params[:summoner_email].to_s.downcase
      @name = params[:summoner].to_s.downcase
      UserMailer.invitation_request(@user, email, @name).deliver_now
      flash[:info] = "Invitation to join LeagueSpec was successfully sent to #{@name.capitalize}."
      redirect_to profile_path(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/home.html.erb
	<div class="profile_view">
		<%= image_tag("fiddlesticks_lol.png") %>
		<div class="profile_view_header">
			<div class="profile_view_header_container">
				<div class="row">
					<div class="profile_view_header_title col-md-8">
						<h3>Welcome to "Player's" LoL Customizable Profile</h3>
					</div>
					<div class="profile_view_header_date col-md-2">
						<h3>Current Date</h3>
					</div>
				</div>	
			</div>
		</div>
	</div>

app/views/profiles/invite.html.erb
<div class="invitation-page">
  <%= render 'search/search_to_invite' %>
</div>

app/views/profiles/new.html.erb
<div class="signup_page authentication_form">
	<div class="row">
		<div class="form-bg form_container col-md-6 col-md-offset-3">
			<%= form_for @user, url: profiles_path(@user), html: { method: :post } do |f| %>
				<%= render 'shared/error_messages' %>

				<%= f.label :name, "Summoner Name" %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :email %>
				<%= f.email_field :email, class: 'form-control' %>

				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control' %>

				<%= f.label :password_confirmation, "Password Confirmation" %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>

				<%= f.submit "Create my account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
	<%= image_tag("signup_banner.png") %>
</div>

app/views/profiles/search.html.erb
<div class = "search-page" id="friend-lookup">
  
  <div class = "col-md-6 col-md-offset-3">
  	<div class="table-responsive">
		  <table class="table search-table" >
		    <thead>
		    	<tr>
		    		<th class="header search-header">Summoner Search Result</th>
		    	</tr>
		    </thead>
		    <tbody>
		      <tr>
		    			<td>
		    			  <% if @friend %>
			    		    <div id="friend-lookup-results" class="row well results-block">
			    		      <div class="col-sm-5">
			    		      	<strong>Summoner Name: <%= @name.capitalize %></strong><br>
			    		        <strong>Summoner Level: <%= @friend.summoner_level %></strong><br>
	                    <strong>Last Active: <%= @friend.revision_date.to_s.slice(0,10) %></strong><br>
			    		      </div>
			    		      <% if @statsObj %>
			    		      	<div class="col-sm-5">
			    		          <strong>Most Played Champ: <%= "#{@mpChamp[:name]}"%> </strong><%= " - (#{@mostPlayedChampObj.stats.total_sessions_played}x)"%> <br>
			    		          <strong>Highest KDR Champ: <%= "#{@hkdrChamp[:name]}"%> </strong> 
			    		                                    <% if @highestKillDeathRatioChampObj[0].stats.total_deaths_per_session >  0 %>
	                                                  <%= " - (#{((@highestKillDeathRatioChampObj[0].stats.most_champion_kills_per_session.to_f)/(@highestKillDeathRatioChampObj[0].stats.total_deaths_per_session)).round(2)})"%>
	                                                <%else%>
	                                                  <%= " - (#{(@highestKillDeathRatioChampObj[0].stats.most_champion_kills_per_session_f.round(2))})"%>
	                                                <%end%><br>
	                      <strong>Highest WLR Champ: <%= "#{@hwlrChamp[:name]}"%> </strong> 
			    		                                    <% if @highestWinLossRatioChampObj[0].stats.total_deaths_per_session >  0 %>
	                                                  <%= " - (#{((@highestWinLossRatioChampObj[0].stats.most_champion_kills_per_session.to_f)/(@highestWinLossRatioChampObj[0].stats.total_deaths_per_session)).round(2)})"%>
	                                                <%else%>
	                                                  <%= " - (#{(@highestWinLossRatioChampObj[0].stats.most_champion_kills_per_session_f.round(2))})"%>
	                                                <%end%><br>
			    		        </div>
			    		        <div class="col-sm-1">
			    		        <!--While this displays a dynamic picture(most played champ), we might need to have users choose their preferred display pictures
			    		          when searched for or on their profile. This could be done when editing profiles.-->
				    		        <%= link_to image_tag("icons/#{@mpChamp[:name].delete(' ')}Square.png"), champion_path(@mpChamp.id)  %>
				    		      </div>
			    		      <% else %>
			    		        <div class="col-sm-6 no-stats">
			    		          <strong>No stats found for summoner.</strong><br>
				    		        <strong>Either summoner is inactive or</strong><br>
		                    <strong>there are no stats to display.</strong><br>
			    		        </div>
			    		      <% end %>
			    		    </div>
			    		  <% else %>
			    		    <div id="friend-lookup-errors" class="well results-block">
			    		      <strong><%= @name.capitalize %> is not a recognized League of Legends player.</strong><br>
			    		      <strong> Verify that <%= @name.capitalize %> is a valid summoner name and try again.</strong><br>
			    		    </div>
			    		  <% end %>
		    		  </td>
		      </tr>
		    </tbody>
		    <tfoot>
		    	<tr>
	    			<td>
		    	  	  <div class="col-sm-12 btn-group btn-group-justified" role="group" aria-label="...">
								  <% if @statsObj %>
									  <% if logged_in? %>
				    			    <% @user = User.find_summoner_by_name(@name) %>
				    			    <% if @user %>
				    			      <div class="btn-group" role="group">
				    			        <%= link_to "Add Friend".html_safe, profile_path(@current_user.id), :class =>"btn btn-success" %>
											  </div>
											  <div class="btn-group" role="group">
											    <%= link_to "View Profile".html_safe, profile_path(@user.id), :class =>"btn btn-default" %>
											  </div>
											<% else %>
	                      <div class="btn-group" role="group">
											    <%= link_to "Invite Friend".html_safe, root_path, :class =>"btn btn-success" %>
											  </div>
											<% end %>
										<% else %>
	                    <div class="btn-group" role="group">
											  <%= link_to "Login".html_safe, login_path, :class =>"btn btn-success" %>
											</div>
											<div class="btn-group" role="group">
											  <%= link_to "Sign Up".html_safe, new_profile_path, :class =>"btn btn-primary" %>
											</div>
				    			  <% end %>
				    			<% end %>
		              <div class="btn-group" role="group">
								    <%= link_to "Dismiss".html_safe, root_path, :class =>"btn btn-danger" %>
								  </div>
								</div>
	    	  	</td>
		    	</tr>
		    </tfoot>
		  </table>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="profile-overview">
  <div class="summoner-header">
		<h1><%= @featured_stats[:summoner].name.capitalize %></h1>
	  <div class="edit-button pull-right">
			<button class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Edit Player Info</button>
		</div>
	</div>
		

	<div class="profile-info">
		<div class="row">
			<div class="col-md-2 profile-pic" >
				<%= image_tag("ahri_lol_small.png", class:"img-circle img-responsive") %>
			</div>
			<div class="bio-table-left col-md-5">
				<table class="bio-text">
				  <tr>
						<th>Summoner Level:</th>
						<td><%= @featured_stats[:summoner].summoner_level %></td>
					</tr>
					<tr>
						<th>Summoner ID:</th>
						<td><%= @featured_stats[:summoner].id %></td>
					</tr>
					<tr>
						<th>Joined LeagueSpec:</th>
						<td><%= @user.created_at.to_s.slice(0,10) %></td>
					</tr>
				</table>
			</div>
			<div class="bio-table-right col-md-5">
				<table class="bio-text">
			  	<tr>
			      <th>Overall KDR:</th>
			      <td><%= @overall_stats[:kd] %></td>
			    </tr>
			    <tr>
						<th>Overall WLR:</th>
						<td><%= @overall_stats[:wl] %></td>
					</tr>
					<tr>
						<th>LoL Last Active:</th>
						<td><%= @featured_stats[:summoner].revision_date.to_s.slice(0,10) %></td>
		      </tr>
			  </table>
			</div>
		</div>
	</div>
</div>

<div class="container spec-social">
	<div class="header champions-header">
		<h3>Featured Champions</h3>
  </div>
  
	<div class="col-md-4">
	  <table class="stats-table">
	  	<tr>
	  		<th colspan="3" class="header"><h4>Ranked by KDR</h4></th>
	  	</tr>
	  	<% @featured_stats[:top_kd].each do |champion| %>
		  	<tr class="champ-row">
		  		<td class="champ-img">
		  			<%= link_to image_tag(champion.icon), champion_path(champion.id) %>
		  		</td>
		  		<td class="stat">
		  			<small>ID: <%= champion.id %></small><br>
						<small>Name: <%= champion.name %></small><br>
						<small>Title: <%= champion.title.titleize %></small><br>
		  		</td>
          <td class="stat right-stat pull-right">
          	<small>Champ Kills: <%= champion.total_kills %></small><br>
						<small>Champ Deaths: <%= champion.total_deaths %></small><br>
						<small>K-D Ratio: <%= champion.kd_ratio %></small><br>
          </td>
		  	</tr>
	  	<% end %>
	  </table>
	</div>

  <div class="col-md-4">
    <table class="stats-table">
	  	<tr>
	  		<th colspan="3" class="header">
	  			<h4>Ranked by WLR</h4>
	  		</th>
	  	</tr>
	  	<% @featured_stats[:top_wl].each do |champion| %>
		  	<tr class="champ-row">
		  		<td class="champ-img">
		  			<%= link_to image_tag(champion.icon), champion_path(champion.id) %>
		  		</td>
		  		<td class="stat">
		  			<small>ID: <%= champion.id %></small><br>
						<small>Name: <%= champion.name %></small><br>
						<small>Title: <%= champion.title.titleize %></small><br>
		  		</td>
	        <td class="stat right-stat pull-right">
	        	<small>Wins: <%= champion.total_wins %></small><br>
						<small>Losses: <%= champion.total_losses %></small><br>
						<small>W-L Ratio: <%= champion.wl_ratio %></small><br>
	        </td>
		  	</tr>
	  	<% end %>
	  </table>
	</div>

	<div class="col-md-4">
    <table class="stats-table">
	  	<tr>
	  		<th colspan="3" class="header">
	  			<h4>Most Played</h4>
	  		</th>
	  	</tr>
	  	<% @featured_stats[:top_played].each do |champion| %>
		  	<tr class="champ-row">
		  		<td class="champ-img">
		  			<%= link_to image_tag(champion.icon), champion_path(champion.id) %>
		  		</td>
		  		<td class="stat">
		  			<small>ID: <%= champion.id %></small><br>
						<small>Name: <%= champion.name %></small><br>
						<small>Title: <%= champion.title.titleize %></small><br>
		  		</td>
	        <td class="stat right-stat pull-right">
	        	<small>Played: <%= champion.total_games %></small><br>
						<small>Wins: <%= champion.total_wins %></small><br>
						<small>Losses: <%= champion.total_losses %></small><br>
	        </td>
		  	</tr>
	  	<% end %>
	  </table>
  </div>
</div>	