config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root    'sessions#new'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'
  delete  'logout'        =>  'sessions#destroy'
  resources :profiles
  get 'invite_user', to: 'profiles#invite'
  get 'send_invitation', to: 'profiles#send_invitation'
  resources :champions, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'search_summoner', to: 'search#search'
  get 'search_to_invite', to: 'search#search_to_invite'
  resources :friendships, only: [:new, :edit, :index, :destroy]
  get 'decide_friendships', to: 'friendships#decide'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @name = params[:summoner]
    if valid_search?
      search_service = BasicStatsService.new(@name)
      @search_stats = search_service.basic_stats
    else 
      redirect_to :back
    end   
  end

  def search_to_invite
    if params[:summoner_name]
      search_service = BasicStatsService.new(params[:summoner_name])
      @person_info = search_service.person_info
      gon.registeredUser = @person_info[:spec_user]
      if @person_info[:spec_user]
        render partial: 'search_to_invite' and return
      end
    end
    if @person_info[:summoner]
      gon.summoner = @person_info[:summoner]
      render partial: 'search_to_invite'
    else
      @search_error = true
      render status: :not_found, nothing: true
    end
  end

  private

  def valid_search?
    if @name.length < 2
      flash[:danger] = "Summoner name must be at least 2 characters, verify summoner name is valid and search again."
      false
    elsif @name.length > 24
      flash[:danger] = "Summoner name must be less than 24 characters, verify summoner name is valid and search again."
      false
    else
      true
    end
  end
end

app/views/search/_search_to_invite.html.erb
<head>
  <%= include_gon %>
</head>
<div id="search-to-invite" class="col-md-8 col-md-offset-2 <%= controller_name %> <%= action_name %>"> 
  <div class="col-md-6 header">LeagueSpec Invitation</div>
  <%= form_tag search_to_invite_path, remote: true, method: :get, id: "search-summoner-form", class: "invitation-form" do %>
    <div class="col-md-12 form-container">
      <div class="row invite-row">
        <div class="col-md-6 invite-field field">
          <%= text_field_tag :summoner_name, params[:summoner_name], class: "form-control search-box", id: "summoner_name", placeholder: "Summoner Name", autofocus: true%>
        </div>
        <div class="col-md-6">
          <span id="summoner_name_feedback", class="feedback">
            <% if @person_info %>
              <% if @person_info[:spec_user] %> 
                Sorry, <%= @person_info[:spec_user].name.capitalize %> is already on LeagueSpec, can't send invitation.
              <% elsif @person_info[:summoner] %> 
                Yes! <%= @person_info[:summoner].name %> is not yet on LeagueSpec. Enter email below to invite.
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-md-offset-2 input-group-btn">
      <%= button_tag(type: :submit, class: "btn btn-success", id: 'sbmt-btn', data: { disable_with: "Initiating invitation..." }) do %>Initiate Invitation
      <% end %>
    </div>
  <% end %>
  
  <%= form_tag send_invitation_path, method: :get, id: "email-summoner-form", class: "email-form" do %>
    <div class="col-md-12 form-container">
      <div class="row summoner-name">
        <div class="col-md-6 summoner">
          <%= hidden_field_tag :summoner, @person_info[:summoner].name if @person_info %>
        </div>
      </div>
      <div class="row invite-row email">
        <div class="col-md-6 invite-field field">
          <%= text_field_tag :summoner_email, params[:summoner_email], class: "form-control summoner-search-box", id: "summoner_email", placeholder: "Summoner Email"%>
        </div>
        <div class="col-md-6">
          <span id="summoner_email_feedback", class="feedback">
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-md-offset-2 input-group-btn">
      <%= button_tag(type: :submit, class: "btn btn-success", id: 'send-btn', data: { disable_with: "Sending invitation..." }) do %>Send Invitation
      <% end %>
    </div>
  <% end %>
</div>

app/views/search/search.html.erb
<div class="search-page" id="summoner-lookup">
  
  <div class="col-md-5 col-md-offset-3">
    <div class="table-responsive">
      <table class="table search-table">
        <thead>
          <tr>
            <th colspan="3" class="header search-header">Summoner Search Result</th>
          </tr>
        </thead>
        <tbody>
          <% if @search_stats.present? %>
            <tr>
              <td><strong>Summoner Name:</strong> <%= @search_stats[:summoner].name %></td>
              <td><strong>Most Played Champ:</strong> <%= @search_stats[:top_played].most_played %></td>
              <td class="champ-img" rowspan="3">
                <%= link_to image_tag(@search_stats[:top_played].icon), champion_path(@search_stats[:top_played].id) %>
              </td>
            </tr>
            <tr>
              <td><strong>Summoner Level:</strong> <%= @search_stats[:summoner].summoner_level %></td>
              <td><strong>Highest KDR Champ:</strong> <%= @search_stats[:top_kd].best_kd %></td>
            </tr>
            <tr>
              <td><strong>Last Active:</strong> <%= @search_stats[:summoner].revision_date.to_s.slice(0,10) %></td>
              <td><strong>Highest WLR Champ:</strong> <%= @search_stats[:top_wl].best_wl %></td>
            </tr>
          <% else %>
            <tr>
              <td class="no-results"><%= "#{@name} is not a recognized League of Legends player." %></td>
            </tr>
            <tr>
              <td class="no-results"><%= "Verify that #{@name} is a valid summoner name and try again." %></td>
            </tr>
          <% end %>
        </tbody>

        <tfoot>
          <tr data-no-turbolink>
            <% if logged_in? %> <!-- Only logged in users can add friends -->
              <% if @search_stats %> <!-- Does the searched user play LoL? -->
                <% if @search_stats[:spec_user] %> <!-- Does player have a LeagueSpec profile? -->
                  <% if @search_stats[:summoner] != current_user %> <!-- Is player the currently logged in user? -->
                    <% if @current_user.friendships.exists?(friend_id: @search_stats[:summoner].id) %> <!-- Is player already a friend? -->
                      <td class="badge"><%= "#{@current_user.friendships.find_by_friend_id(@search_stats[:summoner].id).friendship_status.capitalize} Request" %></td>
                    <% else %>
                      <td><%= link_to "Add Summoner", new_friendship_url(summoner_to_add: params[:summoner]), class: "btn btn-success" %></td>
                    <% end %>
                    <% puts @search_stats[:summoner].id %>
                    <td><%= link_to "View Profile", profile_path(@search_stats[:spec_user].id), class: "btn btn-primary" %></td>
                  <% else %>
                    <td class="badge"><%= "#{@current_user.name.capitalize} is currently logged in." %></td>
                  <% end %>
                <% else %>
                  <td><%= link_to "Invite Friend", invite_user_path, class: "btn btn-primary" %></td>
                <% end %>
                <td colspan="2" scope="colgroup"><%= link_to "Dismiss Search", profile_path(@current_user.id), class: "btn btn-danger" %></td>
              <% else %>
                <td colspan="3" scope="colgroup"><%= link_to "Dismiss Search", profile_path(@current_user.id), class: "btn btn-danger" %></td>
              <% end %>
            <% else %>
              <% if @search_stats %>
                <% if @search_stats[:summoner] %>
                  <td><%= link_to "Login to Add Summoner", login_path, class: "btn btn-success" %></td>
                <% else %>
                  <td><%= link_to "Login to Invite Summoner", login_path, class: "btn btn-success" %></td>
                <% end %>
                <td colspan="2"><%= link_to "Dismiss Search", root_path, class: "btn btn-danger" %></td>
              <% else %>
                <td colspan="3" scope="colgroup"><%= link_to "Dismiss Search", root_path, class: "btn btn-danger" %></td>
              <% end %>
            <% end %>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>