config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root    'sessions#new'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'
  delete  'logout'        =>  'sessions#destroy'
  resources :profiles
  get 'invite_user', to: 'profiles#invite'
  get 'send_invitation', to: 'profiles#send_invitation'
  resources :champions, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'search_summoner', to: 'search#search'
  get 'search_to_invite', to: 'search#search_to_invite'
  resources :friendships, only: [:new, :edit, :index, :destroy]
  get 'decide_friendships', to: 'friendships#decide'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  extend TokenContext
  include Tokenizer
	enum friendship_status: [ :denied, :pending, :accepted]
  attr_accessor :friendship_request_token
	cattr_accessor :daily_request_limit
  @@daily_request_limit = 12
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  belongs_to :friend, foreign_key: 'friend_id', class_name: 'User' 
  validates_presence_of   :user
  validates_presence_of   :friend
  validates_uniqueness_of :friend_id, scope: :user_id
  validate :cannot_request_if_daily_limit_reached
  validates_each :user_id do |record, attr, value|
    record.errors.add attr, 'can not be same as friend' if record.user_id.eql?(record.friend_id)
  end
  before_create :create_friendship_request_digest

  

  def cannot_request_if_daily_limit_reached  
    if new_record? && initiator && user.has_reached_daily_friend_request_limit?
      errors.add(:base, "Daily friends request limit exceeded. Sorry, you'll have to wait a little while before requesting any more friendships.") 
    end
  end 

  def reverse
    Friendship.where('user_id = ? and friend_id = ?', self.friend_id, self.user_id).first
  end

  def self.friends?(user, friend)
    Friendship.exists?(user_id: user.id, friend_id: friend.id, friendship_status: 2)
  end

  def self.denied_friendship?(user, friend)
    Friendship.exists?(user_id: user.id, friend_id: friend.id, friendship_status: 0)
  end

  def self.pending_friendship?(user, friend)
    Friendship.exists?(user_id: user.id, friend_id: friend.id, friendship_status: 1)
  end




  # Sends a friend request email
	def send_friend_request_email
		UserMailer.friendship_request(self).deliver_now
	end

  def create_friendship_request_digest
    self.friendship_request_token = Friendship.new_token
    self.friendship_request_digest = Friendship.digest(friendship_request_token)
  end

  def accept_friend_request
    update(friendship_status: 2, request_responded_at: Time.zone.now)
  end

  def deny_friend_request
    update(friendship_status: 0, request_responded_at: Time.zone.now)
  end


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include SessionsHelper
  before_action :require_user
  before_action :check_or_set_user, except: [:destroy]
  before_action :require_same_user, only: [:edit, :decide]
  FRIENDS_LIST_LENGTH = 5.freeze

  def new
    friend = User.find_by_name(params[:summoner_to_add].to_s.downcase)
    friendship = Friendship.new(:user_id => @user.id, :friend_id => friend.id, :initiator => true)
    reverse_friendship = Friendship.new(:user_id => friend.id, :friend_id =>  @user.id)
    if (friendship.save && reverse_friendship.save)
      friendship.send_friend_request_email
      flash[:info] = "Summoner request sent."
      redirect_to profile_path(@user.id)
    else
      flash[:danger] = 'Failed to add friend.'
      redirect_to :back
    end
  end

  def edit
    friend_service = BasicStatsService.new(current_user.name)
    @friend_stats = friend_service.basic_stats
    friendship ||= get_friendship(@friend_stats[:spec_user].id)
    if friendship.request_responded_at != nil
      flash[:danger] = "You have either accepted or denied that request. If you'd like to add summoner, send a new LeagueSpec request"
      redirect_to profile_path(@user.id)
    end
  end

  def index
    @friends_list_code = params[:friends_list_code]
    if @friends_list_code == 'all'
      @friendships = @user.friendships.accepted
    elsif @friends_list_code == 'active'
      @friendships = @user.get_online_friends
    else 
      @friendships = @user.friendships.pending
    end   
    @friendships = @friendships.paginate(page: params[:page], per_page: FRIENDS_LIST_LENGTH)   
  end

  def decide
    requester ||= get_requester
    friendship ||= get_friendship(requester.id)
    if !Friendship.friends?(@user, requester) 
      if params[:request_token] == 'from-friends-list' || friendship.reverse.authenticated?(:friendship_request, params[:request_token])
        if params[:response_code] == 'accept' 
          friendship.accept_friend_request
          friendship.reverse.accept_friend_request
          flash[:success] = "Summoner request accepted!"
          redirect_to friendships_url(friends_list_code: 'all')
        elsif params[:response_code] == 'deny'
          friendship.deny_friend_request
          friendship.reverse.deny_friend_request
          flash[:notice] = "Summoner request denied!"
          redirect_to friendships_url(friends_list_code: 'all')
        else 
          flash[:notice] = "Summoner request ignored!"
          redirect_to friendships_url(friends_list_code: 'pending')
        end
      else
        flash[:danger] = "Invalid request token. Make sure you click exact request link or request new friendship"
        redirect_to :back
      end
    else
      flash[:danger] = "Unable to process request. Friendship already exists with this summoner."
      redirect_to :back
    end
  end

  def destroy
    friendship ||= Friendship.find(params[:id])
    if friendship
      Friendship.transaction do
        friendship.destroy
        friendship.reverse.destroy
      end
      flash[:notice] = "Summoner deleted!"
      redirect_to friendships_url(friends_list_code: 'all')
    else 
      flash[:danger] = "Unable to process request. Friendship does not exist with this summoner."
      redirect_to :back
    end
  end

  private

  def require_same_user
    if @user != User.find_by(email: params[:friend_email])
      flash[:danger] = "Only summoner requests sent to your email can be accessed. Login to LeagueSpec with the right email and click request link again."
      redirect_to :back
    end
  end

  def get_requester
    User.find_by(email: params[:requester_email])
  end

  def get_friendship(requester_id)
    @user.friendships_not_initiated_by_me.find_by(friend_id: requester_id)
  end
end

app/views/friendships/_friends_list.html.erb
<% friendslist.each do |friendship| %>
<tbody class="friend-row">
	<tr>
		<td ><strong>Summoner Name: <%= friendship.friend.name.capitalize %></strong></td>
		<% if @friends_list_code == 'pending' %> 
		  <td ><strong> <%if friendship.initiator == false %>
		                  Received: 
		                <% else %>
		                  Sent: 
		                <% end %> 
		    <%= time_ago_in_words(friendship.created_at).capitalize %> ago</strong></td>
		<% else %>
		  <td ><strong>Friends Since: <%= time_ago_in_words(friendship.request_responded_at).capitalize %> ago</strong></td>
		<% end %>
	  <td rowspan="3" scope="rowgroup">
      <div class="champ-img">
        <span class="imgWrap"><%= link_to image_tag("icons/AhriSquare.png"), profile_path(friendship.friend.id)  %></span>
        <div class="status-icon">
	        <% if friendship.friend.logged_in %>
	           <%= image_tag("online_icon.png") %>
	        <% elsif friendship.friend.last_logged_in >= (Date.today - 1) %>
	          <%= image_tag("recently_active_icon.png") %>
	        <% else %>
	          <%= image_tag("offline_icon.png") %>
	        <% end %>
        </div>
      </div>
	  </td>
	</tr>
	<tr>
		<td ><strong>Friendship Status: <%= friendship.friendship_status.capitalize %></strong></td>
	  <td ><strong>Member Since: <%= time_ago_in_words(friendship.friend.created_at).capitalize %> ago</strong></td>
	</tr>
	<tr data-no-turbolink>
	  <% if @friends_list_code == 'pending' %> 
	    <%if friendship.initiator == false %>
		    <td><%= link_to  "Accept Request", decide_friendships_path(friend_email: current_user.email, requester_email: User.find(friendship.friend.id).email, request_token: 'from-friends-list', response_code: 'accept'), class: "btn btn-success" %> </td>
		    <td>	<%= link_to  "Deny Request", decide_friendships_path(friend_email: current_user.email, requester_email: User.find(friendship.friend.id).email, request_token: 'from-friends-list', response_code: 'deny'), class: "btn btn-danger" %>
		    </td>
		  <% else %>
		    <td><%= link_to "View Summoner Profile", profile_path(friendship.friend.id), class: "btn btn-success" %></td>
		    <td><%= link_to "Delete Request", friendship_path(id: friendship.id), method: :delete, data: {confirm: "Are you sure you want to delete the request to Summoner #{User.find(friendship.friend.id).name.capitalize}?"}, class: "btn btn-danger" %></td>
	    <% end %>
		<% else %>
		  <td><%= link_to "View Summoner Profile", profile_path(friendship.friend.id), class: "btn btn-success" %></td>
		  <td ><%= link_to "Remove from Summoner List", friendship_path(id: friendship.id), method: :delete, data: {confirm: "Are you sure you want to remove #{User.find(friendship.friend.id).name.capitalize} from Summoner List?"}, class: "btn btn-danger" %></td>
		  
		<% end %>
	</tr>
</tbody>
<% end %>

app/views/friendships/edit.html.erb
<div class="summoner-request-page" id="summoner-request">
  
  <div class="col-md-5 col-md-offset-3">
  	<div class="table-responsive">
		  <table class="table request-table" cellspacing="0" style="border-spacing: 0;">
		    <thead>
		    	<tr>
		    		<th colspan="3" scope="colgroup" class="header request-header">Friend Request from <%= @friend_stats[:spec_user].capitalize %></th>
		    	</tr>
		    </thead>
		    <tbody>
		      <tr>
	        	<td ><strong>Summoner Name: <%= @friend_stats[:spec_user].capitalize %></strong></td>
            <td ><strong>Most Played Champ: <%= @friend_stats[:top_played].most_played %> </strong></td>
        	  <td class="champ-img" rowspan="3" scope="rowgroup"><%= link_to image_tag(@friend_stats[:top_played].icon), champion_path(@friend_stats[:top_played].id)  %></td>
	        </tr>
	        <tr>
	        	<td ><strong>Summoner Level: <%= @friend_stats[:summoner].summoner_level %></strong></td>
	        	<td ><strong>Highest KDR Champ: <%= @friend_stats[:top_kd].best_kd %> </strong></td>
		      </tr>
	        <tr>
	          <td ><strong>Last Active: <%= @friend_stats[:summoner].revision_date.to_s.slice(0,10) %></strong></td>
	          <td ><strong>Highest WLR Champ: <%= @friend_stats[:top_wl].best_wl %> </strong></td>
	        </tr>
		    </tbody>
		    <tfoot>
		      <tr data-no-turbolink>
            <td><%= link_to "Accept Request", decide_friendships_path(friend_email: params[:friend_email], requester_email: params[:requester_email], request_token: params[:id], response_code: 'accept'), class: "btn btn-success" %></td>
            <td ><%= link_to "Deny Request", decide_friendships_path(friend_email: params[:friend_email], requester_email: params[:requester_email], request_token: params[:id], response_code: 'deny'), class: "btn btn-danger" %></td>
            <td ><%= link_to "Ignore Request", decide_friendships_path(friend_email: params[:friend_email], requester_email: params[:requester_email], request_token: params[:id], response_code: 'ignore'), class: "btn btn-default" %></td>
          </tr>
		    </tfoot>
		  </table>
    </div>
  </div>
</div>

app/views/friendships/index.html.erb
<div class="summoner-friends" id="summoner-friends-list">
  <div class="col-md-5 col-md-offset-3">
    <div class="table-responsive">
    	<table class="table friends-list-table">
		    <thead>
		    	<tr>
		    		<th colspan="3" scope="colgroup" class="header friends-list-header">
		    		<% if @friendships.empty? %> 
		    		  <%= "No Summoner Friends" %>
		    		<% elsif @friends_list_code == 'all' %> 
		    		  <%= "All Summoner Friends" %>
		    		<% elsif @friends_list_code == 'active' %>
		    		  <%= "Active Summoner Friends" %>
		    		<% else %>
		    		  <%= "Pending Requests" %>
		    		<% end %>
		    		</th>
		    	</tr>
		    	<tr><th colspan="3" scope="colgroup" class="header" ><%= will_paginate %></th></tr>
		    </thead>
			  <%= render 'friends_list', friendslist: @friendships %>
			  <tfoot>
			    <tr><th colspan="3" scope="colgroup" class="header" ><%= will_paginate %></th></tr>
			  </tfoot>
		  </table>
		</div>
	</div>
</div>