config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root    'sessions#new'
  get     'login'         =>  'sessions#new'
  post    'login'         =>  'sessions#create'
  delete  'logout'        =>  'sessions#destroy'
  resources :profiles
  get 'invite_user', to: 'profiles#invite'
  get 'send_invitation', to: 'profiles#send_invitation'
  resources :champions, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'search_summoner', to: 'search#search'
  get 'search_to_invite', to: 'search#search_to_invite'
  resources :friendships, only: [:new, :edit, :index, :destroy]
  get 'decide_friendships', to: 'friendships#decide'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "League Spec", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Find Player", '#' %></li>
				<li><%= link_to "Champions", '#' %></li>
				<% if logged_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", profile_url(current_user) %></li>
							<li><%= link_to "Settings", '#' %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", logout_path, method: "delete" %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <%= link_to "League Spec", root_path, id: "logo" %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Display user options if logged in. -->
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name.capitalize %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", profile_url(current_user) %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
          <!-- Social Menu options -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">LeagueSpec Social <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Invite to LeagueSpec", invite_user_url %></li>
            <li><%= link_to "All Friends", friendships_url(friends_list_code: 'all') %></li>
            <li><%= link_to "Active Friends", friendships_url(friends_list_code: 'active') %></li>
            <li><%= link_to "Pending Requests", friendships_url(friends_list_code: 'pending') %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    <div class="col-md-3 search-form pull-right">  
      <%= form_tag search_summoner_path, class: "navbar-form", method: :get, id: 'summoner-lookup-form' do %>
        <div class="input-group">
          <%= text_field_tag :summoner, params[:summoner], class: "form-control search-box", placeholder: "Search Summoner ", autofocus: true %>
          <span class="input-group-btn">
            <%= button_tag(type: :submit, class: "btn btn-default") do %>Search
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
          
      
      

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeagueSpec</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
	<%= yield %>
</body>

</html>